Repository quasarframework/quasar, pull requests merged in 2022-01, with the labels that each got.

#12070 fix(ts): Allow ValidationRule to return a Promise (fix: #11854)
  ui/types/api/validation.d.ts
Labels: area/typescript, Qv2 🔝

#12057 fix(VirtualScroll): respect virtualScrollSliceSize #12049
  ui/src/components/virtual-scroll/use-virtual-scroll.js
Labels: Qv2 🔝

#12056 fix(VirtualScroll): respect virtualScrollSliceSize #12049
  ui/dev/src/pages/global/dialog-plugin.vue
  ui/src/mixins/virtual-scroll.js
Labels: Qv1

#12074 fix(LoadingBar): don't overrwrite $q.loadingBar with the bar instance #12059
  ui/dev/src/pages/global/loadingbar.vue
  ui/src/plugins/LoadingBar.js
Labels: Qv1

#12069 feat/fix(Platform): Add detailed types for 'Platform.is' (fix: #12054)
  ui/src/plugins/Platform.js
  ui/src/plugins/Platform.json
Labels: area/typescript, Qv2 🔝, area/plugins

#12131 fix(ui): QInnerLoading spinner props
  ui/src/components/inner-loading/QInnerLoading.js
Labels: Qv1
